// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/proyectos": {
    params: {};
  };
  "/contacto": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/proyectos" | "/contacto";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/proyectos.tsx": {
    id: "routes/proyectos";
    page: "/proyectos";
  };
  "routes/contacto.tsx": {
    id: "routes/contacto";
    page: "/contacto";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/proyectos": typeof import("./app/routes/proyectos.tsx");
  "routes/contacto": typeof import("./app/routes/contacto.tsx");
};